[package]
name = "enigma_apis"
description = "This is a library used to call APIs published on Enigma API"
version = "0.1.1"
license = "MIT"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
x402-rs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
x402-reqwest = { workspace = true }
solana-sdk = { workspace = true }
solana-client = { workspace = true }
reqwest-middleware = "0.4.2"
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
